server:
  port: 8000

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/op?characterEncoding=utf8
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  type-aliases-package: io.op.total.studentClient
  mapper-locations: mybatis/mapper/**/*.xml